with stg_customers as (
    select C_CUSTOMER_ID AS CUSTOMER_ID,
    CONCAT(C_FIRST_NAME,C_LAST_NAME) AS CUSTOMER_NAME,
    C_EMAIL_ADDRESS AS EMAIL_ADDRESS,
    C_CURRENT_ADDR_SK AS CURRENT_ADDRESS,
    C_CUSTOMER_SK as CUSTOMER_SK
    FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
)

SELECT * FROM stg_customers