select c.CUSTOMER_ID,
c.CUSTOMER_NAME,
c.EMAIL_ADDRESS,
c.CURRENT_ADDRESS,
cd.CD_GENDER as GENDER,
cd.CD_CREDIT_RATING as CREDIT_RATING,
cd.CD_PURCHASE_ESTIMATE as PURCHASE_ESTIMATE

from  SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_DEMOGRAPHICS cd 
join {{ ref("stg_customers")}} c
on cd.CD_DEMO_SK=c.CUSTOMER_SK